- group: "今日系列"
  list:
    - icon: zzz
      title: "今日运势"
      desc: "查询今日运势"
    - icon: zzz
      title: "今日CP"
      desc: "今日cp老婆"
- group: "群管理"
  list:
    - icon: 派蒙
      title: "群管/管理菜单"
      desc: "管理Help"
 
- group: "查询"
  list:
    - icon: zzz
      title: "查询好友"
      desc: "已加入好友列表"
    - icon: zzz
      title: "查询群"
      desc: "已加入QQ群列表"
    - icon: zzz
      title: "查询群号"
      desc: "查看当前所在群号"
    - icon: zzz
      title: "联系主人"
      desc: "给设置好的QQ号带话"

- group: "消息推送"
  list:
    - icon: zzz
      title: "推送好友"
      desc: "示列 推送好友 123456789 文本"
    - icon: zzz
      title: "推送群聊"
      desc: "示列 推送群聊 123456789 文本"
    - icon: zzz
      title: "转发推送好友"
      desc: "示列 转发推送好友 123456789 文本"
    - icon: zzz
      title: "转发推送群聊"
      desc: "示列 转发推送好友 123456789 文本"

- group: "管理命令，仅主人可用"
  auth: "master"
  list:
    - icon: zzz
      title: "推送全部好友"
      desc: "顾名思义"
    - icon: zzz
      title: "推送全部群聊"
      desc: "顾名思义"
    - icon: zzz
      title: "#转发推送全部好友"
      desc: "顾名思义"
    - icon: zzz
      title: "#转发推送全部群聊"
      desc: "顾名思义"
    - icon: zzz
      title: "#简单(插件)(强制)更新"
      desc: "更新插件"
